package crimera.patches.twitter.misc.bringbacktwitter.strings

object en_rGB {
    val values = mapOf(
        "conference_default_title" to "Twitter Conference",
        "button_action_add_tweet" to "Add a tweet",
        "button_action_options_tweet" to "Tweet options",
        "button_action_retweet" to "Retweet",
        "button_new_tweet" to "New tweet",
        "button_status_retweeted" to "Retweet (retweeted)",
        "chrome_action_post" to "Tweet",
        "ps__share_post_tweet" to "Tweet",
        "rux_landing_page_title" to "Tweet",
        "tweet_fab_item" to "Tweet",
        "tweet_title" to "Tweet",
        "search_twitter" to "Search Twitter",
        "search_hint" to "Search Twitter",
        "ps__accessibility_retweet_broadcast_button" to "Retweet",
        "shortcut_retweet_tweet" to "Retweet",
        "social_you_retweeted" to "You retweeted",
        "composer_hint_self_thread" to "Add another tweet",
        "confirm_delete_shared_tweet_description" to "Are you sure you want to remove this tweet?",
        "confirm_delete_shared_tweet_title" to "Remove tweet",
        "conversation_control_reply_restricted_dialog_title" to "Tweet not sent",
        "conversation_control_reply_restricted_error" to "Tweet not sent. Replies are restricted.",
        "conversations_alternative_reply_hint" to "Tweet your reply",
        "conversations_other_tweets" to "Other tweets",
        "curation_i_dont_like_this_tweet" to "I don’t like this tweet",
        "date_posted" to "Date tweeted",
        "post_tweet" to "Tweet",
        "deleted_tweet_title" to "This tweet has been deleted.",
        "dm_sensitive_tweet_interstitial_header" to "This tweet may contain sensitive material",
        "dm_untrusted_tweet_interstitial_header" to "This tweet is hidden",
        "empty_profile_tweets_tab_title" to "You haven’t tweeted yet",
        "feedback_action_report_tweet" to "Report tweet",
        "feedback_tweet_unavailable" to "This tweet is unavailable.",
        "filter_item_tweets" to "Tweets",
        "filter_item_tweets_and_replies" to "Tweets & replies",
        "profile_tab_title_timeline" to "Tweets",
        "users_turn_off_retweets" to "Turn off retweets",
        "tweets_retweet" to "Retweet",
        "tweets_retweeted" to "%s retweeted",
        "tweets_undo_retweet_vertical" to "Undo retweet",
        "users_turn_on_retweets" to "Turn on retweets",
        "ps__post_broadcast_twitter" to "Tweet on Twitter",
        "ps__retweet_broadcast_action" to "Retweet on Twitter",
        "retweeters_title" to "Retweeted by",
        "icon_view_tweet_activity" to "View tweet activity",
        "a11y_views_text" to "View tweet activity",
        "tweet_analytics_title" to "Tweet activity",
        "tweets_delete_title" to "Delete tweet",
        "share_tweet_sheet_title" to "Share tweet",
        "view_quote_tweet" to "View tweet",
        "view_tweet" to "View tweet",
        "view_tweet_text" to "View tweet",
        "quote_label_subtitle" to "Add a comment, photo, or GIF before you share this tweet",
        "retweet_label_subtitle" to "Share this tweet with your followers",
        "tweet_added_to_your_bookmarks" to "Tweet added to your Bookmarks",
        "tweet_author" to "Tweet author",
        "tweets_retweeted_accessibility_description" to "Tweeted by %s",
        "tweets_topic_accessibility_description" to "Tweet from topic %s",
        "tweets_unauthorized_error" to "Sorry, you’re not authorized to view these tweets.",
        "ps__posted_on_twitter" to "*%s* tweeted on",
        "ps__retweeted_on_twitter" to "*%s* retweeted on",
        "tweet_removed_from_your_bookmarks" to "Tweet removed from your Bookmarks",
        "a11y_app_bar_x_logo" to "Twitter Logo",
        "a11y_content_description_bonus_content_asset" to "Label on Exclusive content that indicates only Subscribers can see this tweet.",
        "a11y_content_description_vip_badge_asset" to "Subscriber badge appears on your tweets to the people you subscribe to.",
        "a11y_retweet_text" to "view retweet details",
        "about_settings_title" to "About Twitter",
        "account_suspended_description" to "Twitter suspends accounts that violate {{}}Our Rules{{}}.",
        "activity_tab_all_empty_state_description_no_notifications" to "From retweets to likes and a whole lot more, this is where all the action happens about your tweets and followers. You’ll like it here.",
        "activity_tab_all_empty_state_description_no_notifications_from_people_you_follow" to "From retweets to likes and a whole lot more, this is where all the action happens from people you follow",
        "activity_tab_mentions_empty_state_description_no_mentions" to "When someone on Twitter mentions you in a tweet or reply, you’ll find it here.",
        "activity_tab_mentions_empty_state_description_no_mentions_from_people_you_follow" to "When someone you’re following mentions you in a tweet, you’ll see it here.",
        "activity_tab_super_follows_description" to "Likes, mentions, retweets and a whole lot more — when it comes from your subscribers, you’ll find it here.",
        "activity_tab_vit_description" to "Likes, mentions, retweets and a whole lot more — when it comes from a verified account, you’ll find it here. {{}}Learn more{{}}",
        "activity_tab_vit_description_blue_available" to "Likes, mentions, retweets and a whole lot more — when it comes from a verified account, you’ll find it here. {{}}Learn more{{}} Not verified? Subscribe now to get a verified account and join other people in quality conversations.",
        "activity_view_moderated_replies_empty_desc" to "This tweet doesn’t have any hidden replies, but Protected tweets might be filtered out. {{}}Learn more{{}}",
        "add_highlight_description" to "This tweet would be featured in the Highlights tab on your profile.",
        "add_speakers_desc" to "You can invite anyone on Twitter to speak.",
        "add_tweet_button_tooltip_text" to "Add another tweet",
        "add_tweet_to_bookmarks" to "Add tweet to Bookmarks",
        "adding_tweet_to_bookmarks_failed" to "Adding tweet to Bookmarks failed",
        "addressbook_connection_legal" to "Contacts from your address book will be uploaded to Twitter on an ongoing basis to help connect you with your friends and personalise content, such as making suggestions for you and others. You can turn off syncing and remove previously uploaded contacts in your settings. {{}}Learn more{{}}",
        "addressbook_connection_legal_content_description" to "Contacts from your address book will be uploaded to Twitter on an ongoing basis to help connect you with your friends and personalise content, such as making suggestions for you and others. You can turn off syncing and remove previously uploaded contacts in your settings. Tap to learn more.",
        "addressbook_connection_title_content_description" to "Connect your address book to find people you may know on Twitter. Navigate to the bottom of the screen for more info.",
        "admin_tools_entry_reported_tweets" to "Reported tweets",
        "ads_info_why_am_i_seeing_this_promoted_post" to "Why am I seeing this Tweet?",
        "anniversary_landing_action" to "Celebrate with a tweet",
        "anniversary_landing_default_composer" to "Do you remember when you joined Twitter? I do! #MyTwitterAnniversary",
        "anniversary_landing_message" to "Share the big day with others in your Twitter community.",
        "anniversary_landing_title" to "Happy Twitter anniversary!",
        "anyone_can_listen_desc" to "Anyone can listen, including people not logged in to Twitter. {{}}Learn more{{}}",
        "app_icon_content_description_custom_10" to "White Twitter on Earth background",
        "app_icon_content_description_custom_11" to "White Twitter on Moon background",
        "app_icon_content_description_custom_12" to "White Twitter on Mars background",
        "app_icon_content_description_custom_13" to "White Twitter on Stars background",
        "app_icon_content_description_custom_14" to "White Twitter on Cyber background",
        "app_icon_content_description_custom_2" to "White Twitter on magenta background",
        "app_icon_content_description_custom_3" to "White Twitter on purple background",
        "app_icon_content_description_custom_4" to "White Twitter on pink background",
        "app_icon_content_description_custom_5" to "White Twitter on green background",
        "app_icon_content_description_custom_6" to "White Twitter on orange background",
        "app_icon_content_description_custom_7" to "White Twitter on black and white background",
        "app_icon_content_description_custom_8" to "White Twitter on blue, purple and magenta camouflage background",
        "app_name" to "Twitter",
        "app_rating_1_star" to "Rate Twitter app 1 star.",
        "app_rating_2_star" to "Rate Twitter app 2 stars.",
        "app_rating_3_star" to "Rate Twitter app 3 stars.",
        "app_rating_4_star" to "Rate Twitter app 4 stars.",
        "app_rating_5_star" to "Rate Twitter app 5 stars.",
        "app_rating_feedback_email" to "twitter-for-android-feedback@twitter.com",
        "app_rating_feedback_email_body" to "I give the Twitter Android app %d stars because ...",
        "app_rating_prompt_rich_description_initial" to "We’re interested in what you think of the Twitter app. Tap the stars above to rate it.",
        "app_update_title" to "Update your Twitter app",
        "article_tweets_content_description" to "explore tweets in your network that link to this article",
        "author_appeal_label_text" to "We put a warning on this tweet because it might have sensitive content. %s",
        "authorize_app_permission_password" to "See your Twitter password",
        "authorize_app_permission_post" to "Tweet for you",
        "authorize_app_permission_read_tweets" to "Read tweets from your timeline",
        "authorize_app_revoke" to "We recommend reviewing the app’s terms and privacy policy to understand how it will use data from your Twitter account. You can revoke access to any app at any time from the%1\$s section of your Twitter account settings.",
        "authorize_app_twitter_tos" to "By authorising an app you continue to operate under Twitter’s %1\$s. In particular, some usage information will be shared back with Twitter. For more, see our %2\$s.",
        "auto_translation_help_dialog_description" to "Grok will automatically translate based on your Twitter usage and {{}}language settings{{}}. You can also switch the automatic translation settings below.",
        "automation_lp_description" to "Automated accounts are programmed to perform certain actions automatically through the Twitter API. Like posting a region’s weather conditions, for example. They’re created and managed by other people on Twitter.",
        "automation_lp_description_contd" to "Labels let the world know who’s managing the automated account. Once an automated account owner has connected their managing account, a label will appear on the automated account profile and tweets.",
        "av_call_foreground_service_name" to "Twitter calls camera/microphone",
        "av_call_incoming_foreground_service_name" to "Twitter Call Notifications",
        "av_call_permission_subtitle_call_phone" to "Initiate system calls from Twitter",
        "av_docking_explanation" to "Twitter would like permission to play this video on top of other apps so you can keep watching while doing other things.",
        "before_deactivation_to_know_detail_five" to "If you want to download {{}}your Twitter data{{}}, you\'ll need to complete both the request and download process before deactivating your account. Links to download your data cannot be sent to deactivated accounts.",
        "before_deactivation_to_know_detail_four" to "To use your current @username or email address with a different Twitter account, {{}}change them{{}} before you deactivate this account.",
        "before_deactivation_to_know_detail_one" to "You can restore your Twitter account if it was accidentally or wrongfully deactivated for some time after deactivation.",
        "before_deactivation_to_know_detail_one_dynamic" to "You can restore your Twitter account if it was accidentally or wrongfully deactivated for up to %s after deactivation.",
        "block_warning_body" to "Are you sure you want to view these tweets? Viewing tweets won’t unblock %s",
        "blocked_by_tweet_author" to "You are blocked from following this account and viewing their tweets.",
        "blocked_by_user" to "You are blocked from following @%1\$s and viewing @%2\$s’s tweets. {{}}Learn more{{}}",
        "blocked_info" to "You blocked this account. @%s can’t see or reply to your tweets.",
        "blocking_and_muting_learn_more" to "https://help.twitter.com/using-twitter#blocking-and-muting",
        "bonus_content_asset_education_label" to "Only Subscribers can see this tweet",
        "bookmarks_empty" to "Save tweets for later",
        "bookmarks_empty_desc" to "Bookmark tweets to easily find them again in the future.",
        "button_action_delete_tweet" to "Delete tweet %1\$d of %2\$d",
        "button_action_options_view_tweet_details" to "Activate to view tweet details",
        "calling_connection_service_name" to "Twitter Calls",
        "can_moderate_replies_tooltip" to "Hide replies to your tweets",
        "can_unmoderate_replies_tooltip" to "Unhide replies to your tweet",
        "cant_add_tweets_from_protected_accounts" to "You can’t add tweets from protected accounts to your Bookmarks",
        "cashtag_limit_tweet_error" to "Too many cashtags in the tweet",
        "channel_ads_title" to "Twitter for Professionals",
        "channel_audio_tweet_title" to "Audio Tweet Player",
        "channel_engagement_title" to "Related to you and your tweets",
        "channel_generic_title" to "Twitter notices",
        "channel_mute_title" to "Don\'t show these tweets in Home",
        "channel_out_of_network_recommendations_title" to "Recommendations from Twitter",
        "channel_recommendations_title" to "Recommendations from Twitter",
        "channel_tweets_title" to "Tweets from people you follow",
        "channel_unmute_title" to "Show these tweets in Home",
        "checklist_tweet" to "Tweet about your Community",
        "clear_all_bookmarks_confirm_msg" to "This can’t be undone and you’ll remove all tweets you’ve added to your Bookmarks.",
        "clear_all_bookmarks_failed" to "Clearing all tweets from Bookmarks failed",
        "clipping_spaces_part_2_desc_listener" to "Anyone (even listeners) can make clips. The only catch is that you have to be signed into Twitter.",
        "cohost_invite_protected_tweets_warning_text" to "People with {{}}protected tweets{{}} can be heard by everyone when speaking in a Space.",
        "communities_hidden_tweet_title_text" to "Only the author and moderators can see this tweet",
        "communities_removed_member_tweet_description_text" to "When members are removed, their tweets are hidden from the rest of the Community.",
        "community_create_success_dialog_info_text_row_1_access_open" to "All Communities are visible to everyone on Twitter. Anyone can join and/or be invited to your Community.",
        "community_create_success_dialog_info_text_row_1_access_restricted" to "All Communities are visible to everyone on Twitter. People must ask to join your Community, or be invited by the mod team or (if allowed) existing members.",
        "community_create_success_dialog_info_text_row_2" to "• Be kind and respectful. • Keep tweets on topic. • Explore and share.",
        "community_members_info" to "Only Community members can tweet.",
        "community_membership_settings_description" to "Control who can join the community. Know that all Communities are publicly discoverable on Twitter.",
        "community_notification_settings_pinned_tweet" to "Pinned tweets",
        "community_tweet_title" to "Community tweet",
        "composer_edit_tweet" to "Edit tweet %1\$d of %2\$d",
        "composer_tweet_hint" to "Tweet about %s",
        "confirm_mute_description" to "You won’t see {user}’s tweets in your timeline, but you will continue to see notifications. They won’t know they’ve been muted.",
        "conversation_card_cta" to "Tweet %s",
        "conversation_control_composer_bottom_sheet_subtitle" to "Pick who can reply to this tweet. Keep in mind that anyone mentioned can always reply.",
        "conversation_control_cta_content_description" to "Changes who can reply to your tweet",
        "cookies_url" to "https://help.twitter.com/rules-and-policies/twitter-cookies",
        "custom_navigation_intro" to "Customise the navigation bar with your most-used Twitter destinations",
        "delete_bookmark_from_folder_message" to "This will remove the tweet from all Bookmarks and all folders",
        "delete_folder_message" to "Your tweets will still be saved in the \'All Bookmarks\' folder.",
        "description_compose_tweet" to "Tweet %1\$d of %2\$d",
        "dialog_location_message2" to "This lets Twitter collect, store, and use your device’s precise location, such as GPS information, in order to improve your experience — for example, showing you more local content, ads, and recommendations.",
        "dialog_no_location_permission_message" to "Location permission for Twitter is disabled. Enable Location permission for Twitter in App Info &gt; Permissions.",
        "disable_login_verification_confirmation_message" to "If you disable login verification, your phone will no longer be required to log in to Twitter.",
        "dm_a11y_click_tweet" to "Open tweet",
        "dm_a11y_tweet" to "Attached tweet",
        "dm_a11y_tweet_with_gif" to "Attached tweet with gif",
        "dm_a11y_tweet_with_image" to "Attached tweet with image",
        "dm_a11y_tweet_with_link" to "Attached tweet with link",
        "dm_a11y_tweet_with_video" to "Attached tweet with video",
        "dm_empty_prompt_secondary_text" to "Drop a line, share tweets and more with private conversations between you and others on Twitter.",
        "dm_interstitial_view_tweet_link" to "Open tweet",
        "dm_japanese_law_how_we_keep_you_safe_body" to "Twitter systems scan shared links and media for spam, abuse and prohibited content. We also analyse usage patterns to detect suspicious behaviour and improve your experience. We may manually review DMs to investigate reported violations and misuse of our service, or to comply with laws or governmental requests. See our %1\$s for more details.",
        "dm_nsfw_interstitial_description" to "Your tweet media settings are configured to inform you when media may be sensitive.",
        "dm_quick_share_snackbar_shared_tweet_separately" to "Tweet shared individually",
        "dm_quick_share_snackbar_shared_tweet_with_group" to "Tweet shared with group",
        "dm_quick_share_snackbar_shared_tweet_with_user" to "Tweet shared with %1\$s",
        "dm_sent_a_post" to "Sent a tweet",
        "dm_shared_someones_tweet" to "Sent you @%1\$s’s tweet",
        "dm_shared_someones_tweet_in_a_group" to "%1\$s sent @%2\$s’s tweet",
        "dm_shared_someones_tweet_in_a_group_with_message" to "%1\$s sent @%2\$s’s tweet: %3\$s",
        "dm_shared_someones_tweet_with_message" to "Sent you @%1\$s’s tweet: %2\$s",
        "dm_shared_your_tweet_with_you" to "Sent you your tweet",
        "dm_shared_your_tweet_with_you_in_a_group" to "%1\$s sent your tweet",
        "dm_shared_your_tweet_with_you_in_a_group_with_message" to "%1\$s sent your tweet: %2\$s",
        "dm_shared_your_tweet_with_you_with_message" to "Sent you your tweet: %1\$s",
        "dm_support_help" to "https://help.twitter.com/using-twitter/direct-messages#faq",
        "dm_user_sent_a_post" to "%s: Sent a tweet",
        "dm_you_sent_a_post" to "You sent a tweet",
        "dm_you_shared_someones_tweet" to "You sent @%1\$s’s tweet",
        "dm_you_shared_someones_tweet_with_message" to "You sent @%1\$s’s tweet: %2\$s",
        "dm_you_shared_your_own_tweet" to "You sent your own tweet",
        "dm_you_shared_your_own_tweet_with_message" to "You sent your own tweet: %1\$s",
        "drafts_self_thread_count" to "Show %1\$d tweets",
        "drawer_header_soft_user_body" to "Create an official Twitter account to get the full experience.",
        "drawer_header_soft_user_header" to "Join Twitter today",
        "duplicate_tweet_error" to "Duplicate tweet",
        "early_access_edit_tweet_subtitle" to "Edit tweets up to 5 times within 1 hour of posting. Your edit history is visible to anyone who wants to see the evolution of a tweet.",
        "early_access_edit_tweet_title" to "Edit tweet",
        "early_access_longer_video_subtitle" to "Upload videos that are up to 3 hours long on twitter.com and iOS, and up to 10 minutes long on Android.",
        "early_access_longform_subtitle" to "Create tweets, replies and quotes up to 4,000 characters long.",
        "early_access_longform_title" to "Longer tweets",
        "early_access_undo_tweet_subtitle" to "Set a timer to undo sent tweets, and choose which kinds of tweets you want to undo.",
        "early_access_undo_tweet_title" to "Undo tweet",
        "edit_birthdate_explanation" to "This should be the date of birth of the person using the account. Even if you’re making an account for your business, event, or cat. Twitter uses your age to customise your experience, including ads, as explained in our {{}}Privacy Policy{{}}.",
        "edit_birthdate_visibility_description" to "You can control who sees your birthday on Twitter.",
        "edit_expired_message" to "Tweets can only be edited within the first hour after they’re published.",
        "edit_outdated_tweet_navigation_message" to "This is the latest version of this tweet.",
        "edit_pdp_message" to "Edit functionality is limited to original tweets and doesn\'t include things like replies or threads. {{}}Read more{{}} about what you can edit.",
        "edit_tweet_available" to "Edit tweet",
        "edit_tweet_composer_timer_content_description" to "%1\$s, time remaining to edit tweet",
        "edit_tweet_composer_timer_time_left" to "%1\$s remaining to edit tweet",
        "edit_tweet_unavailable_bottom_sheet_body" to "At the moment, only original tweets can be edited, while polls, replies and threads cannot. So, for example, if you start a thread, you won’t be able to edit any of the tweets in it.",
        "edit_tweet_unavailable_bottom_sheet_read_more_body" to "about how Edit tweet works.",
        "edit_tweet_unavailable_bottom_sheet_title" to "Some tweets can’t be edited",
        "edit_tweets_delete_message" to "This will delete all versions of this tweet from your profile, the timeline of any accounts that follow you, and from Twitter search results. This cannot be undone.",
        "editable_tweet_upload_toast_text" to "Your tweet was sent. You have 1 hour to make any edits.",
        "education_prompt_header_title" to "Your tweet was sent",
        "education_prompt_title" to "Help keep Twitter safe and open",
        "election_label_info_message" to "Twitter is partnering with Ballotpedia — a non-profit, civic organisation that publishes an online encyclopaedia of American politics and elections — to help identify accounts for candidates running for US Senate, US House or governor during the 2018 midterm elections.",
        "empty_autoblock_list_subtext" to "When you activate Safety Mode, accounts that Twitter automatically blocks will show up here.",
        "empty_mute_list_subtext" to "Tweets from muted accounts won’t show up in your Home timeline. Mute accounts directly from their profile or tweets. {{}}Learn more{{}}",
        "empty_profile_likes_tab_desc" to "Tap the heart on any tweet to show it some love. When you do, it’ll show up here.",
        "empty_profile_likes_tab_title" to "Like some tweets",
        "empty_profile_other_photos_tab_desc" to "Once they do, those tweets will appear here.",
        "empty_profile_photos_tab_desc" to "Your photo and video tweets will appear here.",
        "empty_profile_super_follow_self_tweets_tab_title" to "You haven\'t tweeted any Subscription tweets yet",
        "empty_profile_super_follow_tweets_tab_desc" to "Subscription tweets will appear here when tweeted",
        "empty_profile_tweets_and_replies_tab_desc" to "When you send tweets or replies, they’ll appear here.",
        "empty_profile_tweets_tab_cta" to "Tweet now",
        "empty_profile_tweets_tab_desc" to "When you tweet a tweet, it’ll show up here.",
        "empty_profile_tweets_tab_profile_onboarding_desc" to "Your tweets will show up here, but let’s set up your profile first.",
        "empty_profile_tweets_tab_profile_onboarding_title" to "New to Twitter?",
        "empty_reported_tweets_message" to "Moderators have taken care of all reported tweets.",
        "empty_state_no_tweets_description" to "Tweets from people in this List will show up here.",
        "empty_state_no_tweets_title" to "Waiting for tweets",
        "empty_timeline_community_title" to "There aren’t any tweets in this Community yet",
        "empty_timeline_desc" to "This is the best place to see what’s happening on Twitter for you. The more people and interests you follow, the better your timeline becomes. We have some suggestions to help you get started.",
        "error_dialog_message" to "Please head over to Shopping Manager on a desktop device (ads.twitter.com/shopping_manager) and try again.",
        "error_timeline_communities" to "Could not retrieve communities tweets. Please try again later.",
        "error_timeline_community" to "Could not retrieve community tweets. Please try again later.",
        "except_blocked_accounts_desc" to "Accounts you’ve blocked won’t be able to join. However, people not logged in to Twitter may be able to listen. {{}}Learn more{{}}",
        "exclusive_timeline_tweet_education_message" to "You can see this tweet because you Subscribe to @%s",
        "exclusive_tweet_reply_education_title" to "Who can see this tweet?",
        "favorite_ambient_notification" to "%1\$s liked your tweet",
        "feedback_privacy_notice_format" to "View %1\$s’s %2\$s. Twitter may also use your feedback. %3\$s.",
        "fifth_preload_notification_body" to "Add your thoughts to the conversation on Twitter.",
        "first_moderated_reply_education_description" to "To give you more control over the conversations you start, tweet authors can hide replies to their tweets. Hidden replies are moved to a separate page, and anyone can view them by selecting the hidden reply icon on the tweet. {{}}Learn more{{}}",
        "first_moderated_reply_education_title" to "Hiding replies to your tweets",
        "first_preload_notification_body" to "People on Twitter are the first to know.",
        "fleet_spacebar_ticker_tweet_count" to "%1\$s tweets",
        "fleet_spacebar_ticker_user_shared_a_tweet" to "%1\$s shared a tweet here",
        "folder_empty_state_description" to "When you Bookmark a tweet, you can add it to this folder.",
        "for_you_recommendations_setting_description" to "When this setting is enabled, Twitter may personalise your For You content based on your Twitter activity. {{}}Learn more{{}}",
        "fourth_preload_notification_body" to "Share your opinion on Twitter.",
        "funny_grok_stories_summary" to "View latest stories on Twitter in Grok fun mode.",
        "gif_fab_label" to "Tweet GIF",
        "global_mentions_settings_confirm_disable_description" to "No one will be able to mention you in tweets, threads or replies.",
        "global_mentions_settings_subtitle" to "Control who mentions you in tweets, threads and replies.",
        "go_to_twitter" to "Go to twitter.com",
        "golive__tip_broadcaster_10" to "&lt;b&gt;TIP:&lt;/b&gt; Thank you for going live on Twitter! &lt;3",
        "golive__tip_pre_broadcast_6" to "&lt;b&gt;TIP:&lt;/b&gt; That’s all the tips we have for now — thanks for going live on Twitter!",
        "graduated_user_prompt_header" to "You’ve unlocked more on Twitter",
        "grok_data_share_preference_description" to "Twitter may share with xAI your Twitter public data as well as your user interactions, inputs and results with Grok on Twitter to train and fine-tune Grok and other AI models developed by xAI. This helps us continuously improve your user experience. {{}}Learn more{{}}",
        "grok_explain_post_item_title" to "Explain this tweet",
        "grok_personalization_preference_description" to "Twitter may share with xAI your Twitter data as well as your user interactions, inputs and results with Grok to personalise your experience with Grok and other AI models developed by xAI. This helps us continuously improve your user experience. {{}}Learn more{{}}",
        "grok_personalization_preference_title" to "Allow your Twitter data as well as your interactions, inputs, and results with Grok to be used for personalising your Grok experience",
        "grok_share_attachment_agent_mode_post_analysis_response" to "Tweet analysis by Grok",
        "grok_share_attachment_post_unavailable_message" to "This tweet is unavailable.",
        "hashtag_limit_tweet_error" to "Too many hashtags in tweet",
        "history_management_header_fmt" to "Here are all the Spaces you’ve recorded. You can listen to them, share them or even delete them. Keep in mind that Twitter will always keep a copy of each Space for at least 30 days after a Space has ended. {{}}Learn more{{}}",
        "home_logout_despite_logout_verification_lockout" to "We can’t disable login verification on your account at the moment. If you continue, you will be locked out of Twitter unless you have your back-up code.",
        "home_logout_question_default" to "Logging out will remove all Twitter data from this device.",
        "home_logout_question_enrolled_pending" to "Logging out will unenrol your account from login verification and you will lose your pending tweets.",
        "home_logout_question_pending" to "Logging out will remove all Twitter data from this device, including your pending tweets.",
        "identity_education_conditions" to "I consent to Twitter and Au10tix using images of my ID and my selfie, including extracted biometric data, to confirm my identity and for Twitter’s related safety and security purposes, including preventing impersonation. Au10tix may store such data for up to 30 days. {{}}Learn more{{}}",
        "identity_education_conditions_eea" to "I consent to Twitter sharing images of my ID, including biometric data, and personal data from my profile with Au10tix for the purpose of confirming my identity. I also consent to Twitter storing my ID images, including biometric data, for up to 30 days and using it and data from my profile for the purposes of safety and security, including preventing impersonation. {{}}Learn more{{}}",
        "identity_education_conditions_persona_vendor" to "I agree to Twitter and Persona using images of my ID and my selfie, including extracted biometric data, to confirm my identity and for Twitter’s related safety and security, fraud prevention, and payment purposes. Persona may store such data for up to 30 days. Twitter may store full name, address, and hashes of my document ID number for as long as I subscribe to the Twitter Blue service. {{}}Learn more{{}}",
        "illegal_media_upload_warning" to "If you upload any Illegally Filmed Content, Twitter may delete or block access to the content and the uploader may be sanctioned.",
        "immediate_dismiss_header_text" to "Tweet hidden",
        "immediate_dismiss_sub_header_text" to "You’ll see fewer tweets like this. Any other feedback?",
        "interact_with_this_tweet" to "Interact with this tweet",
        "invalid_thread_tweet_button_description" to "Tweet %d is invalid",
        "last_edit_message" to "Your tweet can’t be updated again.",
        "learn_more_about_twitter_recording" to "Twitter always keeps copies of Spaces for a limited time to review for spam and abuse. {{}}Learn more{{}}",
        "learn_more_anonymous_users" to "Only the top 500 guests can be shown.There might be people listening who aren’t logged in to Twitter. {{}}Learn more{{}}",
        "leave_community_prompt_description" to "You’ll lose access to the Community and will no longer be able to participate, but your previous tweets will still be visible.",
        "leave_conversation_dialog_message" to "This will untag your username from the original tweet and all replies. People can’t mention you again in this conversation and you won’t receive further notifications.",
        "leave_conversation_prompt_untag_username_subtitle" to "Your username stays, but it’ll be untagged from the original tweet and all replies.",
        "like_action_sheet_like" to "Like this tweet",
        "like_confirm_message" to "Like this tweet?",
        "list_mute_subtitle" to "Top tweets from this List will no longer show up in your Home timeline.",
        "list_no_tweets_description" to "This List does not have any tweets yet.",
        "list_no_tweets_title" to "No tweets",
        "list_unmute_subtitle" to "Top tweets from this List may show up in your Home timeline.",
        "live_event_default_timeline_title" to "Tweets",
        "live_event_timeline_no_tweets_description" to "Check back later to see tweets about this.",
        "live_event_video_geoblocked_error" to "This broadcast is not available in your location, but you can still check out the tweets.",
        "live_video_geoblocked_playback_error_message" to "Unfortunately, licence restrictions prevent video viewing in your location. But they can’t stop you from enjoying the tweets!",
        "loading_new_tweets_banner" to "Checking for new tweets",
        "lockscreen_permission_error" to "Please unlock your device to allow Twitter access to your camera.",
        "login_title_seamful" to "Log in to Twitter.",
        "login_verification_add_a_phone_message" to "You must have a phone associated with your Twitter account to use this feature.",
        "login_verification_welcome_take_screenshot" to "This device is now required to log in to Twitter. Would you like to take a screenshot of your back-up code and store it in your Android Gallery app? You’ll need this code if you lose this device!",
        "manage_subscription_stripe_description" to "Looks like you bought this subscription on twitter.com. You\'ll need to manage or cancel your subscription from that platform.",
        "max_tweets_early_warning_tooltip_text" to "Add up to 5 more tweets",
        "max_tweets_tooltip_text" to "You can add more tweets to this thread after sending these.",
        "media_quote_tooltip" to "Retweet with a GIF, video or photos",
        "mention_limit_tweet_error" to "Too many mentions in tweet",
        "message_unable_to_edit" to "Unable to edit tweet",
        "mixed_media_nux_description" to "We’re testing a feature that lets you add multiple types of media to a single tweet. Go ahead, mix things up.",
        "mixed_media_nux_title" to "Photos, videos, and GIFs — in one tweet",
        "mixed_media_remove_tag_question" to "Are you sure you want to remove the tag from this tweet?",
        "moderated_interstitial_default_label_text" to "This reply has been hidden by the tweet author",
        "moments_cover_tweet_attribution" to "Tweet via %s",
        "mute_confirmation_message_not_following_tweets" to "You won’t see tweets from @%s or get notifications about them. They won’t know they’ve been muted.",
        "mute_confirmation_message_tweets" to "You won’t see @%s’s tweets in your timeline, but you will continue to see notifications. They won’t know they’ve been muted.",
        "mute_list_tweets_and_fleets" to "Tweets and Fleets",
        "muted_keywords_v2_education" to "When you mute words, you won’t get any new notifications for tweets that include them or see tweets with those words in your Home timeline. {{}}Learn more{{}}",
        "narrowcast_participation_limited_content" to "Communities are public, so you can read the tweets – but currently participation is invite-only.",
        "narrowcast_polls_not_allowed_content" to "To tweet into the Community, you\'ll need to delete your poll first.",
        "narrowcast_protected_account_content" to "Communities are public, so protected accounts can\'t join the conversation. You can read and like the tweets, but to do more, you\'ll need to make your tweets public.",
        "narrowcast_protected_account_title" to "Your tweets are protected",
        "new_tweets_banner" to "New tweets",
        "new_user_prompt_header" to "Unlock more on Twitter",
        "new_user_prompt_subheader" to "To make Twitter great for everyone, we want to make sure there’s a human behind this account. Help us learn by spending time engaging with your timeline and connecting with others. When we’re confident, you can do the following:",
        "news_camera_video_permissions_prompt_subtitle" to "Allow Twitter access to your camera, media and microphone to use the improved Twitter camera.",
        "news_reader_mode_subtitle" to "Set the text size you prefer for reading threads. Turn the Reader feature on by selecting “View thread in Reader” from within any tweet in a thread.",
        "news_subtitle" to "A better reading experience on and off Twitter.",
        "no_tweets" to "No tweets",
        "non_compliant_summary_sheet_description" to "We try to keep Twitter a place for healthy conversation, so we’ve disabled most of the ways to engage with this tweet. If you want to talk about it, you can still quote it. {{}}Learn More{{}}",
        "non_compliant_summary_sheet_title_retweet" to "Why can’t you retweet this?",
        "notif_sending_edit" to "Editing tweet…",
        "notif_sending_edit_success" to "Tweet edited",
        "notif_sending_self_thread_summary" to "Sending tweet %1\$d of %2\$d…",
        "notif_sending_self_thread_title" to "Sending your tweets",
        "notif_sending_thread_success" to "Tweets sent",
        "notif_sending_tweet" to "Sending tweet…",
        "notif_sending_tweet_success" to "Tweet sent",
        "notification_tweet_to" to "Tweet to…",
        "ntp_see_new_posts" to "See new tweets",
        "option_delete_tweet" to "Delete tweet",
        "option_hide_tweet" to "Hide tweet",
        "option_report_tweet" to "Report tweet",
        "option_share_tweet" to "Share tweet via...",
        "original_tweets" to "Original tweets",
        "outdated_callout_focal_tweet" to "There\'s a new version of this tweet.",
        "outdated_callout_tweet" to "There\'s a new version of this tweet",
        "parody_commentary_fan_account_settings_description" to "This label ensures people on Twitter are not confused by your account, informing them that your account is not affiliated with the subject of the profile. {{}}Learn more{{}}",
        "parody_commentary_fan_account_settings_disable_dialog_message" to "Turning off this label will remove it from your profile and all past tweets. Please check you are compliant with the Authenticity policy.",
        "participated_limited_community_prompt_description" to "Communities are public, so you can read the tweets — but currently, participation is invite-only.",
        "password_change_failure" to "Oops! We weren’t able to set your password. Please go to https://twitter.com/account/begin_password_reset to reset your password",
        "payment_disclaimer_footer_text" to "Twitter Payments LLC is a financial technology company, and not a bank. Funds are held at Cross River Bank, Member FDIC, and are eligible for pass through FDIC insurance if certain conditions are satisfied.",
        "payment_eligibility_default_content_title" to "Twitter Money isn’t ready for you yet",
        "payment_funds_insurance_footer_text" to "Your deposits are eligible for pass through FDIC insurance up to $250,000. Twitter is a financial services company and not a bank. Banking services and FDIC insurance is provided by Cross River Bank, Member FDIC.",
        "payment_identity_verification_benefit_1_subtitle" to "Your personal information is safe and secure with Twitter",
        "payment_identity_verification_content_subtitle" to "Unlock the full benefits of Twitter Money by confirming who you are.",
        "payment_onboarding_document_verification_disclaimer_text" to "I consent to Twitter and Socure using images of my ID and my selfie, including extracted biometric data, to confirm my identity and for Twitter’s related safety and security purposes.",
        "payment_restricted_us_state_content_subtitle" to "Your account is limited until Twitter Money becomes available in {state}.",
        "payment_restricted_us_state_content_title" to "Twitter Money is not available in {state}",
        "payment_restricted_us_state_failure_content_subtitle" to "We’re not able to complete your identity verification until Twitter Money becomes available in {state}",
        "payment_restricted_us_state_failure_unknown_content_subtitle" to "We’re not able to complete your identity verification until Twitter Money becomes available in your state.",
        "payment_restricted_us_state_unknown_content_subtitle" to "Your account is limited until Twitter Money becomes available in your state.",
        "payment_restricted_us_state_unknown_content_title" to "Twitter Money is not available in your state",
        "payment_settings_enhanced_privacy_requests_option_description" to "Only people you follow can request money from you on Twitter.",
        "payment_settings_enhanced_privacy_transfers_option_description" to "Only people you follow can send you money on Twitter.",
        "payment_settings_security_privacy_pin_unlock_payment_option_description" to "To access your balance and other features related to Twitter Money.",
        "payment_shutdown_content_subtitle" to "A newer version of Twitter is available, and is required to use Money.",
        "payments_passkey_setup_benefit_3_subtitle" to "Your account will be secured everywhere you use Twitter",
        "pcf_account_lp_pcf_benefits_description_format" to "Yes. The PCF label ensures people on Twitter are not confused by your account, informing them that your account is not affiliated with the subject of the profile. If not labelled, your account may violate the Authenticity policy.",
        "pending_tweet_cancel_discard_confirm" to "Discard tweet",
        "pending_tweet_cancel_title" to "Do you want to delete this tweet? It will be saved to drafts.",
        "pending_tweet_cancel_title_discard" to "Do you want to discard this tweet?",
        "pending_tweet_cancel_title_no_draft" to "Do you want to cancel sending this tweet?",
        "permission_dialog_retargeting_message" to "%s permissions can be enabled under Settings &gt; Apps &gt; Twitter &gt; Permissions",
        "photos_fab_label" to "Tweet photos",
        "pin_added_to_highlights" to "Tweet has been pinned and added to highlights",
        "pin_community_tweet_confirmation_message" to "This will appear at the top of the Community feed and replace any previously pinned tweets.",
        "pin_confirmation_message" to "This will appear at the top of your profile and replace any previously pinned tweet.",
        "pin_confirmation_title" to "Pin this tweet",
        "pin_hashtags_description" to "Pin hashtags to organise your community\'s tweets on separate timelines",
        "pin_reply_confirmation_message" to "It will appear at the top of your tweet\'s replies and replace any existing pinned replies.",
        "pin_reply_confirmation_title" to "Pin reply to your tweet?",
        "pin_reply_nux_body" to "Now you can pin a reply to your tweet using the actions menu — those three little dots on a tweet (…).",
        "pinned_tweet" to "Pinned tweet",
        "pinning_failed_message" to "Failed to pin this tweet. Please try again later",
        "post_details_post_your_reply" to "Tweet your reply",
        "post_details_title" to "Tweet",
        "post_engagements" to "Tweet Engagements",
        "post_notifs_all_posts_and_replies_confirmation" to "You’ll get notifications for new Tweets &amp; replies.",
        "post_notifs_all_posts_and_replies_description" to "Get notifications for this account’s Tweets &amp; replies.",
        "post_notifs_all_posts_and_replies_title" to "All Tweets &amp; Replies",
        "post_notifs_all_posts_confirmation" to "You’ll get notifications for new Tweets.",
        "post_notifs_all_posts_description" to "Get notifications for all of this account’s Tweets.",
        "post_notifs_all_posts_title" to "All Tweets",
        "post_notifs_live_confirmation" to "You’ll get notifications for new Live video Tweets.",
        "post_notifs_off_confirmation" to "You’ll no longer get notifications for new Tweets.",
        "post_notifs_off_description" to "Turn off notifications for this account’s Tweets.",
        "post_notifs_subscription_confirmation" to "You’ll get notifications for new Subscription Tweets.",
        "post_notifs_subscription_description" to "Get notifications only for Subscription Tweets.",
        "post_notifs_subscription_title" to "Only Subscription Tweets",
        "post_photo" to "Tweet Photo",
        "post_quit_title" to "Save tweet?",
        "post_self_thread" to "Tweet all",
        "post_tweet_error" to "Failed to send tweet",
        "post_video" to "Tweet Video",
        "privacy_policy_url" to "https://twitter.com/privacy",
        "private_account_banner_reply_cant_see" to "They can’t view this reply because you’ve protected your tweets.",
        "pro_category_sheet_desc" to "Categories are self-selected and not assigned, verified or endorsed by Twitter. {{}}Learn more.{{}}",
        "product_drop_compose_tweet" to "Compose tweet",
        "product_image_message" to "• File types: GIF, JPEG, or PNG • Minimum dimensions: 500 twitter 500 pixels • Max size: 8 MB",
        "profile_blocked_by_me_button" to "View tweets",
        "profile_blocked_by_me_description" to "Are you sure you want to view these tweets? Viewing tweets won’t unblock {formatted_screen_name}",
        "profile_interstitial_sensitive_media_body" to "You’re seeing this warning because they tweet potentially sensitive images or language. Do you still want to view it?",
        "profile_mute_state_message_tweets" to "You have muted tweets from this account",
        "profile_search" to "Search tweets",
        "profile_smart_blocked_autoblocked_by_twitter_description" to "You’re temporarily autoblocked from viewing and interacting with @%1\$s’s tweets. This happened when they were in Safety Mode, and we flagged your interactions as potentially abusive or spammy. We know that we don’t get autoblocks right all the time, so we’re working to improve our detection. {{}}What’s%2\$sSafety%2\$sMode?{{}} Here are ways to keep your conversations healthy — and avoid being autoblocked.",
        "profile_smart_blocked_autoblocked_by_twitter_title" to "Autoblocked by Twitter",
        "profile_smart_blocked_remember_the_human_description" to "There’s a person on the other end of your tweet with feelings.",
        "profile_suspended_account_message" to "Twitter suspends accounts that violate the {{}}Rules{{}}.",
        "profile_tab_articles_empty_description" to "When you publish an Article on twitter.com it will show up here.",
        "profile_tab_articles_empty_title" to "Write Articles on Twitter",
        "profile_tab_articles_upsell_empty_description" to "When you publish an Article on twitter.com it will show up here. Only Blue+ subscribers can publish Articles.",
        "profile_tab_highlights_empty_description" to "To add Highlights to your profile: 1. Find any tweet you created 2. Tap the “⋮” menu button 3. Tap “Add/remove from Highlights”",
        "profile_tab_highlights_empty_title" to "Show off your best tweets!",
        "profile_tab_highlights_upsell_empty_description" to "You must be Verified to highlight tweets on your profile.",
        "profile_tab_title_posts" to "Tweets",
        "profile_tooltip_account_notif" to "Never miss a tweet with notifications",
        "profile_tooltip_account_notif_variation_1" to "Get notifications for new tweets",
        "profile_tooltip_account_notif_variation_2" to "Never miss when they tweet or go live",
        "profile_tooltip_account_notif_variation_3" to "Know when your fave account tweets",
        "profile_tooltip_account_notif_variation_4" to "Turn on notifications for new tweets",
        "promoted_tweet" to "Promoted tweet",
        "protected_account_participated_limited_prompt_description" to "Communities are public, so protected accounts can’t join at the moment. You can read the tweets, but to participate, make your tweets public.",
        "protected_account_participated_limited_prompt_title" to "Your tweets are protected",
        "protected_account_share_disclaimer" to "Some sharing options aren’t available on protected tweets",
        "protected_tweet_title" to "This tweet is not available because it\'s from a protected account.",
        "ps__accessibility_chat_row_twitter_icon" to "Twitter",
        "ps__action_sheet_open_twitter_profile" to "Go to Twitter Profile",
        "ps__broadcast_following_chat_off" to "Everybody can tweet chats",
        "ps__broadcast_following_chat_on" to "Only users you follow can tweet chats",
        "ps__chat_prompt_guest_banned_twitter" to "*@%s* was reported, reviewed by Twitter, and found to be violating the Rules.",
        "ps__chat_share_screenshot_twitter" to "Share screenshot and broadcast on *Twitter*",
        "ps__copyright_violation_whitelisted_broadcaster_modal_description_format_with_copyright_title_and_holder" to "This broadcast matches “%1\$s”, a copyrighted work by %2\$s. Do you have all rights necessary to broadcast this video on Twitter?",
        "ps__edit_broadcast_banner_description" to "Editing your broadcast changes the way it will look for people who see it. These changes will not affect any tweets or Notifications that have already occurred.",
        "ps__featured_twitter" to "Following on Twitter",
        "ps__hydra_pick_call_in_type_disclaimer_line_two" to "Everyone watching on Periscope or Twitter will see that you\'ve joined %1\$s\'s broadcast and hear you. This may include people you\'ve blocked on either app.",
        "ps__install_description" to "Broadcast LIVE to your Twitter followers with Periscope",
        "ps__share_post_tweet_success" to "Tweet sent!",
        "ps__tip_pre_broadcast_5" to "&lt;b&gt;TIP:&lt;/b&gt; Share your broadcasts on Twitter to reach more viewers.",
        "ps__tweet_broadcast_failed" to "We encountered an error sharing your broadcast on Twitter. Please try again.",
        "quick_promote_nux_sheet_title" to "Try boosting this tweet!",
        "quote_tweet_interstitial_text" to "This quoted tweet is unavailable.",
        "quote_tweets_timeline_empty_state_description" to "Add your take when sharing someone else’s tweet and it’ll appear here.",
        "reaction_group_user_to_other_tweet" to "%1\$s reacted to @%2\$s\'s tweet with %3\$s",
        "reaction_group_user_to_your_tweet" to "%1\$s reacted to your tweet with %3\$s",
        "reaction_them_to_tweet" to "%1\$s reacted to a tweet with %3\$s",
        "reaction_you_to_group_tweet" to "You reacted to @%2\$s\'s tweet with %3\$s",
        "reaction_you_to_tweet" to "You reacted to a tweet with %3\$s",
        "recorded_spaces_indefinite_replay_desc" to "Listen to the recording at any time. You can also share it with a tweet.",
        "recorded_spaces_learn_more_text" to "Twitter always keeps copies of Spaces for a limited time to review for spam and abuse. {{}}Learn more{{}}",
        "recording_prompt_subtext" to "Twitter will keep a recording of Spaces for at least 30 days to review reports. {{}}Learn more{{}}",
        "remove_all_contacts_message" to "This removes any contacts you’ve previously uploaded and turns off address book syncing with Twitter on all your devices. Please be aware that this takes a little time.",
        "remove_highlight_description" to "This tweet would be removed from the Highlights tab on your profile.",
        "removed_member_cannot_join_community_prompt_description_2" to "Your tweets in the Community will be hidden, and you won’t be able to join again.",
        "removing_tweet_from_bookmarks_failed" to "Removing tweet from Bookmarks failed",
        "reply_to_deleted_tweet_error" to "Can’t reply to a deleted tweet",
        "report_bug_finished" to "Thanks! Though we cannot respond to individual reports, the information provided helps us make Twitter better for everyone. We appreciate your help!",
        "report_description" to "Let Twitter know about spam or abuse so we can help protect others from accounts like this",
        "reported_interstitial_default_label_text" to "You reported this tweet.",
        "reported_tweets_hidden_by_admin" to "You hid @%s\'s tweet",
        "reported_tweets_kept_by_admin" to "You kept @%s\'s tweet",
        "reported_tweets_nux_inline_callout_header" to "Reported tweets view",
        "reported_tweets_nux_inline_callout_subtext" to "This is the place where all reported tweets will show up. As a moderator, you’ll be able to take proper actions on tweets that have been reported by other members.",
        "reported_unavailable_tweets_message" to "This tweet is unavailable.",
        "retweet_action_sheet_subtitle_for_verbose_annotation" to "Retweets allow you to publicly share someone else\'s tweet with your followers. You can forward tweets you love, news you want to share or fun discoveries.",
        "retweet_action_sheet_title_for_verbose_annotation" to "How retweets work",
        "retweet_ambient_notification" to "%1\$s retweeted your tweet",
        "retweet_dialog_all_links_nudge_prompt_title" to "You’re about to share a link you haven’t opened on Twitter. {{}}Learn more{{}}",
        "retweet_dialog_article_nudge_prompt_title" to "You’re about to share an article you haven’t opened on Twitter. {{}}Learn more{{}}",
        "retweet_protected_education_description" to "Only people who follow @%s can view their tweets.",
        "retweet_protected_education_title" to "Protected tweets can’t be retweeted",
        "retweet_with_comment2" to "Retweet with comment",
        "retweeted_by_timeline_empty_state_description" to "Share someone else’s tweet on your timeline by reposting it. When you do, it’ll appear here.",
        "retweeted_by_timeline_empty_state_title" to "Amplify tweets you like",
        "rich_behavior_mute_list_confirmation" to "Top tweets from this List will no longer appear in Home",
        "rich_behavior_unmute_list_confirmation" to "Top tweets from this List may show up in Home",
        "room_action_tweet_about_space_description" to "Tweet about this Space",
        "room_settings_delete_recording_prompt_desc" to "If you delete your recording, no one will be able to listen to your Space once it’s ended. Twitter will still keep a copy of this Space for at least 30 days to review for spam and abuse.",
        "room_settings_share_via_tweet" to "Share via tweet",
        "safety_education_prompt_block_description" to "Blocking someone removes all their tweets from your timeline, prevents them from following or messaging you, and you won’t see notifications from them.",
        "safety_education_prompt_mute_description" to "Muting someone removes their tweets from your timeline — without unfollowing or blocking them.",
        "safety_education_prompt_report_description" to "Tell us if you think this tweet is harmful, abusive or breaks any of our rules.",
        "safety_education_prompt_report_subheading" to "Report tweet",
        "safety_education_prompt_subtitle" to "Access the following safety features using the actions menu — those three little dots on a tweet (•••).",
        "safety_education_prompt_title" to "How to stay safe on Twitter",
        "safety_education_prompt_unfollow_description" to "Unfollowing someone removes all their tweets from your timeline.",
        "safety_mode_autoblocked_tweets" to "Autoblocked tweets",
        "safety_mode_flagged_tweets" to "Flagged tweets",
        "safety_mode_settings_half_sheet_description_2" to "Autoblocked accounts, just like manually blocked accounts, can’t see your tweets, follow you or message you. If they view your profile, we let them know that Twitter autoblocked them, and not you.",
        "safety_mode_settings_half_sheet_title_1" to "Twitter does the work, so you don’t have to",
        "save_tweet_to_bookmarks" to "Save a tweet to read later by saving it to your Bookmarks",
        "schedule_calendar_description" to "Join this Space on Twitter: %s",
        "schedule_notifications_alert_message_consumer" to "Turn on push notifications for Twitter to get reminded when this Space starts.",
        "schedule_notifications_alert_message_creator" to "Turn on push notifications for Twitter.",
        "schedule_notifications_alert_title_consumer" to "Let Twitter notify you?",
        "schedule_tickets_terms" to "All ticket sales are final. By purchasing a ticket you agree to the {{}}Twitter Purchaser Terms of Service{{}}",
        "search_settings_description" to "Searchable tweets",
        "search_subscribe_toast" to "You\'re subscribed to receive push notifications for tweets about \'%1\$s\'",
        "search_subscribe_turn_on_recommendations_prompt_body" to "To get notifications for this search, you need to enable Notifications &gt; \'Recommendations from Twitter\' in your settings",
        "search_unsubscribe_toast" to "You\'re no longer subscribed to receive push notifications for tweets about \'%1\$s\'",
        "search_username_tweets" to "Search %s’s tweets",
        "second_preload_notification_title" to "The world talks on Twitter",
        "self_thread_sent_in_app_message_text" to "Tweets successfully sent",
        "sending_tweet" to "Sending tweet…",
        "sensitive_content_setting_description" to "This prevents tweets with potentially sensitive content from displaying in your search results.",
        "sensitive_media_description" to "Select a category, and we’ll put a content warning on this tweet. This helps people avoid content that they don’t want to see.",
        "sensitive_media_description_title" to "Put a content warning on this tweet",
        "sensitive_media_interstitial_message" to "The tweet author flagged this tweet as showing sensitive content.",
        "setting_twitter_business" to "Twitter for Business",
        "settings_2fa_item_detail" to "Protect your account from unauthorised access by requiring a second authentication method in addition to your Twitter password. You can choose a text message, authentication app, or security key. {{}}Learn more{{}}",
        "settings_accessibility_alt_text_prompt_summary" to "Enables a reminder to add image descriptions before a tweet can be sent.",
        "settings_accessibility_at_twitter" to "Accessibility at Twitter",
        "settings_accessibility_at_twitter_learn_more_title" to "Learn more about accessibility at Twitter",
        "settings_accessibility_detail" to "Manage how Twitter content is displayed to you.",
        "settings_accessibility_double_tap_to_like_summary" to "Adds the ability to double-tap anywhere on a tweet to like it.",
        "settings_accessibility_pref_detail" to "Manage aspects of your Twitter experience such as limiting colour contrast and motion. These settings affect all the Twitter accounts on this device.",
        "settings_additional_resources_item_detail" to "Check out other places for helpful information to learn more about Twitter products and services.",
        "settings_ads_business_partners_detail" to "Allow sharing of additional information with Twitter’s business partners.",
        "settings_ads_prefs_item_detail" to "Manage your ads experience on Twitter.",
        "settings_app_language_subtitle" to "Your preferred language for headlines, buttons and other text from Twitter.",
        "settings_audience_item_detail" to "Manage what information you allow other people on Twitter to see.",
        "settings_badge_summary" to "Displays a badge with the number of notifications waiting for you inside the Twitter app.",
        "settings_connected_accounts_detail" to "These are the social accounts you connected to your Twitter account to log in. You can disable access here.",
        "settings_connected_accounts_item_detail" to "Manage Google or Apple accounts connected to Twitter to log in.",
        "settings_content_you_see_item_detail" to "Decide what you see on Twitter based on your preferences.",
        "settings_data_saver_summary" to "When enabled, videos won’t autoplay and lower-quality images load. This automatically reduces your data usage for all Twitter accounts on this device.",
        "settings_data_sharing_item_detail" to "Allow sharing of additional information with Twitter’s business partners.",
        "settings_data_sharing_summary" to "Twitter always shares information with business partners as a way to run and improve its products. When enabled, this allows Twitter to share additional information with those partners to help support running Twitter’s business, including making Twitter’s marketing activities on other sites and apps more relevant for you. {{}}Learn more{{}}",
        "settings_data_sync_summary" to "Allow Twitter to sync data in the background to enhance your experience.",
        "settings_data_usage_item_detail" to "Limit how Twitter uses some of your network data. These settings affect all the Twitter accounts on this device.",
        "settings_deactivate_for_soft_user_item_detail" to "Find out how you can deactivate and exit your current Twitter experience.",
        "settings_delete_phone_summary" to "This deletes the phone number from this account, and you’ll no longer receive notifications as text messages from Twitter.",
        "settings_email_disco_summary" to "People who have your email address will be able to connect with you on Twitter.",
        "settings_email_notifications_from_twitter_title" to "From Twitter",
        "settings_email_notifications_from_you_section_title" to "Related to you and your tweets",
        "settings_email_notifications_send_activation_email" to "Tips on getting more out of Twitter",
        "settings_email_notifications_send_email_newsletter" to "News about updates to Twitter products and features",
        "settings_email_notifications_send_network_digest" to "Top tweets and Stories",
        "settings_email_notifications_send_partner_email" to "News about Twitter on partner products and other third-party services",
        "settings_email_notifications_send_performance_digest" to "Updates about the performance of your tweets",
        "settings_email_notifications_send_resurection_email" to "Things you’ve missed since you last logged in to Twitter",
        "settings_email_notifications_send_shared_tweet_email" to "Tweets emailed to you",
        "settings_email_notifications_send_smb_sales_marketing_email" to "Tips on Twitter business products",
        "settings_email_notifications_send_survey_email" to "Participation in Twitter research surveys",
        "settings_email_notifications_summary" to "Control when and how often Twitter sends emails to you.",
        "settings_in_app_browser_summary" to "Open external links with Twitter browser",
        "settings_inferred_identity_item_detail" to "Allow Twitter to personalise your experience with your inferred activity, e.g. activity on devices you haven’t used to log in to Twitter.",
        "settings_interest_based_ads_summary" to "You will always see ads on Twitter based on your Twitter activity. When this setting is enabled, Twitter may further personalise ads from Twitter advertisers, on and off Twitter, by combining your Twitter activity with other online activity and information from our partners. {{}}Learn more{{}}",
        "settings_language_subtitle" to "Select which languages you want recommended tweets, people, and trends to include.",
        "settings_languages_item_detail" to "Manage which languages are used to personalise your Twitter experience.",
        "settings_link_devices_summary" to "Twitter will always personalise your experience based on information you’ve provided, as well as the devices you’ve used to log in. When this setting is enabled, Twitter may also personalize based on other inferences about your identity, like devices and browsers you haven\'t used to log in to Twitter or email addresses and phone numbers similar to those linked to your Twitter account. {{}}Learn more{{}}",
        "settings_location_access_summary" to "Twitter always uses some information, like where you signed up and your current location, to help show you more relevant content. When this setting is enabled, Twitter may also personalise your experience based on other places you’ve been.",
        "settings_location_info_item_detail" to "Manage the location information Twitter uses to personalise your experience.",
        "settings_login_verification_summary" to "Verify all login requests to Twitter using this device.",
        "settings_mark_media_sensitive_title" to "Mark media you tweet as containing material that may be sensitive",
        "settings_monetization_summary" to "See how you can make money on Twitter and manage your monetisation options.",
        "settings_news_subtitle" to "Discover relevant long form tweets and enjoy articles being shared in your network.",
        "settings_no_location_permission_message" to "Location permission for Twitter is disabled. Enable Location permission for Twitter in {{}}App Info{{}}.",
        "settings_notif_timeline_title" to "Tweets",
        "settings_notif_tweets_live_follow_summary" to "Get notifications when people tweet or share live videos. These will be push or SMS notifications, depending on your settings. {{}}Learn more{{}}",
        "settings_notification_from_twitter" to "From Twitter",
        "settings_other_languages_subtitle" to "Additional languages for the content you want to see on Twitter.",
        "settings_password_protection_item_detail" to "For added protection, you\'ll need to confirm your phone number or email address to reset your Twitter password.",
        "settings_phone_disco_summary" to "People who have your phone number will be able to connect with you on Twitter.",
        "settings_precise_location_summary" to "If enabled, Twitter will collect, store and use your device’s precise location, such as GPS information. This lets Twitter improve your experience — for example, showing you more local content, ads and recommendations.",
        "settings_privacy_learn_more_section_title" to "Learn more about privacy on Twitter",
        "settings_privacy_safety_item_detail" to "Manage what information you see and share on Twitter.",
        "settings_protect_videos_summary" to "If selected, videos you tweet or send via DMs will not be downloadable by default. This setting applies to videos shared going forwards and is not retroactive. {{}}Learn more{{}}",
        "settings_protected_summary" to "Only current followers and people you approve in the future will be able to see your tweets. {{}}Learn more{{}}",
        "settings_protected_title" to "Protect your tweets",
        "settings_sensitive_media_category_summary" to "Manage your preferences for seeing sensitive media on Twitter. Learn more about our {{}}sensitive media policy{{}}.",
        "settings_sensitive_media_warn_description" to "Hide media marked as %s until you choose to see it. On Twitter for iOS, this media won’t be shown at all.",
        "settings_twitter_activity_section_title" to "Your Twitter activity",
        "settings_twitter_data_header_title" to "Twitter data",
        "settings_twitter_data_learn_more_url" to "https://help.twitter.com/managing-your-account/accessing-your-twitter-data",
        "settings_two_factor_auth_summary" to "Protect your account from unauthorised access by requiring a second authentication method in addition to your Twitter password. You can choose text message, authentication app or security key. {{}}Learn%1\$smore{{}}",
        "settings_your_tweets_item_detail" to "Manage the information associated with your tweets.",
        "settings_your_tweets_item_title" to "Your tweets",
        "settings_your_twitter_data" to "See your Twitter data",
        "share_email_conditions" to "Share your email with %1\$s. By accepting, you agree to let Twitter share the email address with the creator for the purpose of off-platform communication and accept the {{}}Email address sharing terms{{}}. {{}}Learn More{{}}",
        "share_space_anonymous_users" to "Share with people outside of Twitter",
        "share_via_tweet" to "Share via tweet",
        "shop_disclaimer_text" to "By clicking \'Save\' and publishing a Shop Spotlight, you agree to be bound by our {{}}Twitter Shopping Policies{{}}.",
        "shortcut_disabled_reason" to "This shortcut can no longer be used with Twitter for Android",
        "shortcut_navigate_compose" to "New tweet",
        "shortcut_navigate_next" to "Next tweet",
        "shortcut_navigate_previous" to "Previous tweet",
        "shortcut_open_tweet" to "Open tweet details",
        "shortcut_tweet" to "New tweet",
        "show_more_posts" to "Show more tweets",
        "show_more_tweets" to "Show more tweets",
        "similar_posts_label_text" to "Related tweets",
        "simple_tweets_protected_body" to "Only confirmed followers have access to @%s’s tweets and complete profile. Tap the \'Follow\' button to send a follow request.",
        "sixth_preload_notification_body" to "Follow who (and what) inspires you on Twitter.",
        "smart_block_warning_body" to "You turned on Safety Mode, so we autoblocked %1\$s for a week. The autoblock ends in %2\$s. You can view their profile to learn more about them, or go to their autoblocked tweets to see why we autoblocked them. Neither one of these actions will unblock %1\$s.",
        "smart_block_warning_view_flagged_tweets" to "View autoblocked tweets",
        "social_context_education_prompt_description" to "Follow the %s Topic for more top tweets or select twitter to remove this recommendation.",
        "soft_intervention_like_nudge_expanded_label" to "Help keep Twitter a place for reliable info. Find out more before liking this tweet.",
        "soft_intervention_nudge_expanded_label" to "Help keep Twitter a place for reliable info. Find out more before sharing this tweet.",
        "soft_intervention_pivot_engagements_disabled" to "This tweet can’t be replied to, shared or liked.",
        "soft_intervention_pivot_government_required" to "Twitter is legally required to provide this notice.",
        "sort_post_bottom_sheet_title" to "Sort tweets",
        "space_nudge_share_tweet" to "Share with a tweet",
        "space_nudge_share_tweet_description" to "*Tweet* your Space. Let’s get people in here.",
        "spaces_card_reminder_share" to "Share with a tweet",
        "spaces_card_report_success_toast_text" to "Thanks. This will help us make your Twitter experience better.",
        "spaces_rules_url" to "https://help.twitter.com/rules-and-policies/twitter-rules",
        "spaces_settings_mic_subtitle_go_to_settings" to "Please enable microphone permissions for Twitter in your device’s settings",
        "spaces_tooltip_down_caret" to "Browse Twitter while you listen",
        "spaces_tooltip_find_tweets_to_share" to "Find tweets to share in your Space",
        "spaces_tooltip_share_tweet" to "Tap to share a tweet in the Space",
        "spaces_tooltip_share_tweet_to_space" to "Tap to share a tweet in your Space",
        "spaces_tooltip_speaker_down_caret" to "Find tweets to share in this Space",
        "spaces_tooltip_tweet_from_space" to "Tweet about what\'s happening in this Space",
        "spaces_tweet_shared_in_space" to "Tweet shared in %1\$s",
        "spammer_blocked_tweet_message" to "To protect our users from spam and other malicious activity, this account is temporarily blocked from sending tweets. Please make sure you understand our rules.",
        "super_follow_badge_description" to "Allow anyone to see your Subscriber badge when you reply to @%1\$s’s tweets",
        "super_follow_badge_explanation" to "When you turn this off, @%1\$s and their Subscribers will still see your badge when you reply to @%1\$s’s Subscribers-only tweets. @%1\$s will always see your badge. {{}}Learn more{{}}",
        "super_follow_subscription_subtitle" to "Support your favourite people on Twitter for bonus content and extra perks",
        "super_follows_subscription_terms" to "By clicking below to make this purchase, you agree to be bound by the {{}}Twitter Purchaser Terms{{}}. Cancel anytime. Auto-renews monthly.",
        "survey_subtext" to "These surveys help Twitter and its partners improve advertising.",
        "suspended_account_dialog_message" to "Your account (@%s) is currently suspended. For more information, please log in to twitter.com.",
        "switch_account_composer_confirmation_dialog_description" to "After you tweet, you’ll still be logged in as @%1\$s.",
        "switch_account_composer_confirmation_dialog_title" to "You’re about to tweet on behalf of a delegate account",
        "switch_account_confirmation_dialog_description_admin" to "Remember that this account does not belong to you. As an admin, you can send Direct Messages, publish tweets and create Lists — as well as view them. You can also invite or remove contributors to the account and view account analytics. {{}}Learn more{{}}",
        "switch_account_confirmation_dialog_description_contributor" to "Remember that this account does not belong to you. As a contributor, you can send Direct Messages, publish tweets and create Lists — as well as view them. {{}}Learn more{{}}",
        "teams_contributees_deny_system_settings_logout" to "If you’d like to remove yourself from a team, go to tweetdeck.twitter.com and click on Accounts.",
        "this_quoted_post_is_unavailable" to "This quoted tweet is unavailable",
        "timecode_share_sheet_tweet" to "New tweet",
        "tipjar_confirmation_rationale_profile" to "Tip how much you want. No money goes to Twitter. When tipping, you’ll be subject to the third-party platform’s terms. That means that your name, phone number, email and other personal information might be shared with the tip recipient.",
        "tipjar_disclaimer_dialog_description" to "Tipping is subject to the third-party platform’s terms, including what information is shared about people sending money to one another. No money goes to Twitter.",
        "tipjar_terms_bullet_fans_desc" to "You drive the conversation and we want to make it easier for people to support your work beyond Follows, Retweets and Likes.",
        "tipjar_terms_cards_money_desc" to "People will be able to send you cash from your profile. No money goes to Twitter.",
        "tipjar_terms_title" to "Get cash instantly from your followers on Twitter",
        "tipjar_terms_why_tips_desc" to "Tips are an easy way to support the incredible voices that make up the conversation on Twitter. Here\'s how it works.",
        "tipjar_twitter_terms_of_service" to "Twitter Terms of Service",
        "tos_url" to "https://twitter.com/tos",
        "totp_description" to "Enter this code to log in to your Twitter account.",
        "toxic_original_tweet_with_mention_nudge_description_collective_good" to "We’re asking people to review tweets that mention others and include potentially harmful or offensive language. Want to take another look before posting?",
        "toxic_original_tweet_with_mention_nudge_description_descriptive_norm" to "We’re asking people to review tweets that mention others using potentially harmful or offensive language. Want to take another look before posting?",
        "toxic_original_tweet_with_mention_nudge_description_injunctive_norm_line_2" to "We’re asking people to review tweets with potentially harmful or offensive language. Want to take another look before posting?",
        "toxic_original_tweet_with_mention_nudge_title_collective_good" to "Tweet about others the way you want to be tweeted about",
        "toxic_original_tweet_with_mention_nudge_title_descriptive_norm" to "Most posters don’t mention others in tweets like this",
        "toxic_original_tweet_with_mention_nudge_title_injunctive_norm" to "Tweet about others the way you want to be tweeted about.",
        "toxic_reply_nudge_expanded_description_injunctive_norm_line_2" to "We’re asking people to review tweets with potentially harmful or offensive language. Want to take another look before posting?",
        "toxic_reply_nudge_expanded_description_loss_frame_line_1" to "Tweets like this might be sectioned lower in the conversation and be seen by fewer people.",
        "toxic_reply_nudge_expanded_title_collective_good" to "Help make Twitter better for everyone",
        "toxic_reply_nudge_expanded_title_descriptive_norm" to "Most posters don’t tweet replies like this",
        "toxic_reply_nudge_expanded_title_injunctive_norm" to "Tweet about others the way you want to be tweeted about.",
        "toxic_reply_nudge_expanded_title_loss_frame" to "Fewer people might see your tweet",
        "toxic_reply_nudge_primary_button" to "Tweet",
        "toxic_survey_description_primary" to "We want to keep Twitter a place for meaningful conversations. So when we detect potentially harmful or offensive language in a reply — like insults, strong language or hateful remarks — we sometimes ask people if they want to review it before sending.",
        "translatable_benefits_badge_subtitle" to "You\'ll get a public Subscriber label on your tweets so I can easily pick you out in a crowd",
        "translate_tweet_error" to "Unable to translate this tweet. Please try again later.",
        "translate_tweet_same_language" to "This tweet is already in %s",
        "translate_tweet_show" to "Translate tweet",
        "trusted_friends_focal_message" to "Only people in @%s’s Circle can see this tweet. {{}}Learn more{{}}",
        "trusted_friends_focal_message_default" to "Only people in this Circle can see this tweet. {{}}Learn more{{}}",
        "trusted_friends_share_disclaimer" to "Some sharing options aren’t available on Circle tweets. {{}}Learn more{{}}",
        "trusted_friends_timeline_message" to "Only people in @%s’s Circle can see this tweet.",
        "trusted_friends_timeline_message_default" to "Only people in this Circle can see this tweet",
        "tweet_about_experience" to "Tweet about your experience",
        "tweet_accessibility_text_latest_edit" to "This is the latest version of this tweet",
        "tweet_actions_disabled" to "Some actions on this tweet have been disabled by Twitter.",
        "tweet_conversation_show_more_replies_desc" to "Show more replies to %1\$s\'s tweet",
        "tweet_detail_outdated_callout_see_latest_description" to "open the new version of this tweet",
        "tweet_dislike_leave_behind" to "Thanks. Twitter will use this to make your timeline better.",
        "tweet_edit_sent_in_app_message_text" to "Your tweet has been edited",
        "tweet_is_already_in_your_bookmarks" to "Tweet is already in your Bookmarks",
        "tweet_is_bounce_deleted" to "This tweet is no longer available because it violated the rules. {{}}Learn more{{}}",
        "tweet_is_bounced" to "This tweet is no longer available. {{}}Learn more{{}}",
        "tweet_length_percent" to "Tweet length at %1\$s",
        "tweet_load_failed" to "Failed to load tweet.",
        "tweet_load_see_more_threads_failed" to "Tweet didn’t load.",
        "tweet_location_message" to "Enable to add a location to your tweets.",
        "tweet_location_title" to "Tweet location",
        "tweet_moderate_failure" to "There was an error hiding the tweet. Please try again.",
        "tweet_moderate_success" to "Reply hidden from tweet",
        "tweet_sent_in_app_message_text" to "Your tweet was sent",
        "tweet_this" to "Tweet this",
        "tweet_unmoderate_failure" to "There was an error unhiding the tweet. Please try again.",
        "tweet_visibility_education_dialog_description" to "Only your followers can view your tweets and replies.",
        "tweet_visibility_education_dialog_title" to "You protected your tweets",
        "tweets_delete_status_error" to "Cannot delete tweet. Please try again later.",
        "tweets_expired_question" to "We’re sorry, we weren’t able to send %1\$d of your tweets. Would you like to try sending them again or save these tweets in drafts?",
        "tweets_fetch_error" to "Cannot retrieve tweets at this time. Please try again later.",
        "tweets_get_status_error" to "Cannot retrieve tweet at this time. Please try again later.",
        "tweets_protected_title" to "These tweets are protected.",
        "tweets_retweet_error" to "Cannot retweet status.",
        "tweets_retweet_subtitle_exclusive" to "Only Subscribers can see this retweet.",
        "tweets_share_subject_long_format" to "Tweet from %1\$s (@%2\$s)",
        "twitter_blue_edit_upsell_bottom_sheet_body" to "Twitter Blue subscribers get early access to features such as Edit, which lets you update a tweet up to 5 times within the first hour after it’s published.",
        "twitter_data" to "Twitter",
        "twitter_intent_handling_title" to "Twitter",
        "two_factor_auth_re_enter_password" to "Re-enter your Twitter password to save changes to your account.",
        "two_factor_authentication_no_network_dialog_title" to "Can’t connect to Twitter",
        "two_factor_settings_2fa_u2f_security_key_add_key_description" to "You’ll be logged in to twitter.com on your browser to add a security key. If you’re already logged in on another account, we’ll automatically log you out of it.",
        "two_factor_settings_2fa_u2f_security_key_ineligible_enroll_description" to "Currently, you can add a security key to your Twitter account only when you’re logged in to twitter.com on a compatible web browser.",
        "two_factor_settings_2fa_u2f_security_key_ineligible_enroll_title" to "You can’t add a security key on the Twitter mobile app",
        "two_factor_settings_2fa_u2f_security_key_manage_key_description" to "You’ll be logged in to twitter.com on your browser to rename or delete a security key. If you’re already logged in on another account, we’ll automatically log you out of it.",
        "two_factor_settings_backup_code_summary" to "Get a single-use back-up code so you can log in to Twitter if you don’t have access to any of your two-factor authentication methods. {{}}Learn more{{}}",
        "two_factor_settings_delete_phone_and_turn_off_2fa" to "This deletes the phone number from this account, and you’ll no longer receive notifications as text messages from Twitter. Additionally, this turns off two-factor authentication on this account.",
        "two_factor_settings_delete_phone_with_and_disable_sms_2fa" to "This deletes the phone number from this account, and you’ll no longer receive notifications as text messages from Twitter. Additionally, this turns off text messaging as a two-factor authentication method on this account.",
        "two_factor_settings_mobile_authenticator_summary" to "Use an app to get an authentication code to enter when you log in to Twitter.",
        "two_factor_settings_no_verified_email_dialog_description" to "To turn on two-factor authentication, you need to associate an email address with this Twitter account and then confirm it, so we know it’s really yours.",
        "two_factor_settings_text_message_summary" to "Use your mobile phone to receive a text message with an authentication code to enter when you log in to Twitter.",
        "two_factor_settings_u2f_security_key_summary" to "Use a physical security key that inserts into your computer or syncs to your mobile device when you log in to twitter.com using a supported web browser. Currently, you can’t use a security key to log in to the Twitter app. {{}}Learn more{{}}",
        "two_factor_settings_u2f_security_key_summary_enabled" to "Use a security key that inserts into your computer or syncs to your mobile device when you log in to Twitter. You’ll need to use a supported mobile device or web browser. {{}}Learn more{{}}",
        "undo_nudge_toxic_prompt_description" to "This tweet might contain strong language.",
        "undo_nudge_toxic_prompt_title" to "Keep Twitter safe and open",
        "undo_tweet" to "Undo tweet",
        "undo_tweet_period" to "Undo tweet timing",
        "undo_tweet_pref_summary" to "Select which types of tweets you want to undo before they\'re public, plus how long your undo period is.",
        "undo_tweet_title" to "Undo tweet",
        "unmute_confirmation_message" to "Tweets from this account will now be allowed in your Home timeline.",
        "unpin_community_tweet_confirmation_message" to "This tweet will no longer show up at the top of the Community feed.",
        "unpin_confirmation_title" to "Unpin tweet from your profile?",
        "unpin_reply_confirmation_message" to "It will no longer appear at the top of this tweet\'s replies.",
        "unpinning_failed_message" to "Failed to unpin this tweet. Please try again later",
        "unsupported_media_entry" to "Twitter doesn\'t support image insertion here",
        "update_available" to "This version of Twitter is out of date. To keep using the app, install the latest version on the Google Play Store. {{}}Learn more{{}}",
        "update_copyright" to "© 2023 Twitter Inc",
        "update_from_store" to "This version of Twitter is out of date. To keep using the app, install the latest version. {{}}Learn more{{}}",
        "upload_contacts_disconnect_summary" to "Remove any contacts you’ve previously uploaded and turn off syncing with Twitter on all devices. Please be aware that this takes a little time.",
        "upload_contacts_summary" to "Contacts from your address book will be uploaded to Twitter on an ongoing basis to help connect you with your friends and personalise content, such as making suggestions for you and others. Turning off syncing will not remove previously uploaded contacts. {{}}Learn more{{}}",
        "url_dm_abuse_interstitial_learn_more" to "https://help.twitter.com/safety-and-security/report-a-tweet",
        "url_limit_tweet_error" to "Too many links in tweet",
        "use_a_temporary_password_message" to "You will need to generate a temporary password on twitter.com to continue.",
        "users_block_message_when_view_enabled" to "They will be able to see your public tweets, but will no longer be able to engage with them. @%1\$s will also not be able to follow or message you, and you will not see notifications from them.",
        "users_change_friendship_dialog_message" to "Or turn off notifications when they tweet.",
        "users_destroy_friendship_message" to "Their tweets will no longer appear in your home timeline. You can still view their profile, unless their tweets are protected.",
        "users_device_follow_recommendation_dialog_message" to "You are now following %s. Would you like us to notify you when they tweet?",
        "users_device_follow_recommendation_dialog_title" to "Turn on tweet notifications",
        "users_device_follow_success" to "You will now receive notifications when %s tweets.",
        "users_device_unfollow_dialog_title" to "Turn off tweet notifications",
        "users_device_unfollow_question_dialog_message" to "You will stop receiving notifications when %s tweets.",
        "users_remove_autoblock_question" to "They will be able to see your tweets, follow you and send you Direct Messages.",
        "users_turn_off_retweets_success" to "Retweets from %s will no longer appear in your timeline",
        "users_turn_on_retweets_success" to "Retweets from %s will appear in your timeline",
        "users_tweet_notifications_dialog_message" to "You will now receive notifications whenever they tweet.",
        "users_tweet_notifications_dialog_title" to "Tweet notifications",
        "users_unblock_message" to "They will be able to follow you and view your tweets.",
        "users_unblock_message_when_view_enabled" to "They will be able to follow you and engage with your tweets. (If the account is protected they\'ll have to re-request to follow)",
        "verification_protected_desc" to "This account has its tweets protected. Only their followers can read them.",
        "video_long_blue_suggestion" to "Subscribe to Twitter Blue to tweet longer videos.",
        "video_long_desktop_recommendation" to "The best way to tweet long videos is to use www.twitter.com on a desktop computer.",
        "view_count_dialog_description" to "Times this tweet was seen. To learn more, visit the {{}}Help Centre{{}}.",
        "view_count_dialog_description_unavailable" to "Times this tweet has been seen. It can take a few minutes for the view count to appear. To learn more, visit the {{}}Help Centre{{}}.",
        "welcome_to_communities_dialog_description" to "Communities are moderated discussion groups where people on Twitter can connect and share.",
        "welcome_to_communities_dialog_info_text_row_2" to "Your tweets are shared with Community members and your followers.",
        "welcome_to_communities_dialog_info_title_row_2" to "Tweet directly to a Community",
        "what_is_a_backup_code" to "If you ever lose your device, you will need this code to access your Twitter account. Please write it down.",
        "will_deactivate_account" to "You’re about to start the process of deactivating your Twitter account. Your display name, @username and public profile will no longer be viewable on Twitter.com, Twitter for iOS or Twitter for Android.",
        "will_deactivate_soft_user_account" to "By selecting this option, you’ll deactivate and exit your current Twitter experience. You’re always welcome to return to Twitter; you won’t be able to access the set of accounts that you currently follow, but you can refollow each account when you return.",
        "will_deactivate_soft_user_account_title" to "This will deactivate your current Twitter experience",
        "x_lite_add_highlight_description" to "This tweet would be featured in the Highlights tab on your profile.",
        "x_lite_button_action_add_tweet" to "Add a tweet",
        "x_lite_button_action_delete_tweet" to "Delete tweet %1\$d of %2\$d",
        "x_lite_button_action_options_tweet" to "Tweet options",
        "x_lite_channel_generic_title" to "Twitter notices",
        "x_lite_composer_hint_self_thread" to "Add another tweet",
        "x_lite_conversation_control_composer_bottom_sheet_subtitle" to "Pick who can reply to this tweet. Keep in mind that anyone mentioned can always reply.",
        "x_lite_conversations_alternative_reply_hint" to "Tweet your reply",
        "x_lite_delete_bookmark_from_folder_message" to "This will remove the tweet from all Bookmarks and all folders",
        "x_lite_deleted_tweet_title" to "This tweet has been deleted.",
        "x_lite_dialog_no_location_permission_message" to "Location permission for Twitter is disabled. Enable Location permission for Twitter in App Info &gt; Permissions.",
        "x_lite_filter_item_tweets" to "Tweets",
        "x_lite_fleet_spacebar_ticker_tweet_count" to "%1\$s tweets",
        "x_lite_funny_grok_stories_summary" to "View latest stories on Twitter in Grok fun mode.",
        "x_lite_grok_share_attachment_agent_mode_post_analysis_response" to "Tweet analysis by Grok",
        "x_lite_option_delete_tweet" to "Delete tweet",
        "x_lite_option_report_tweet" to "Report tweet",
        "x_lite_payment_disclaimer_footer_text" to "Twitter Money is a financial technology company, and not a bank. Bank accounts are held at Cross River Bank, Member FDIC.",
        "x_lite_payment_funds_insurance_footer_text" to "Your deposits are eligible for pass through FDIC insurance up to $250,000. Twitter is a financial services company and not a bank. Banking services and FDIC insurance is provided by Cross River Bank, Member FDIC.",
        "x_lite_payment_identity_verification_benefit_1_subtitle" to "Your personal information is safe and secure with Twitter",
        "x_lite_payment_identity_verification_content_subtitle" to "Unlock the full benefits of Twitter Money by confirming who you are.",
        "x_lite_payment_onboarding_document_verification_disclaimer_text" to "I consent to Twitter and Socure using images of my ID and my selfie, including extracted biometric data, to confirm my identity and for Twitter’s related safety and security purposes.",
        "x_lite_payment_restricted_us_state_content_subtitle" to "You can still view your balance, but actions are currently disabled until Twitter Money becomes available in {state}.",
        "x_lite_payment_restricted_us_state_content_title" to "Twitter Money is not available in {state}",
        "x_lite_payment_restricted_us_state_failure_content_subtitle" to "We’re not able to complete your identity verification until Twitter Money becomes available in {state}",
        "x_lite_payment_restricted_us_state_failure_unknown_content_subtitle" to "We’re not able to complete your identity verification until Twitter Money becomes available in your state.",
        "x_lite_payment_restricted_us_state_unknown_content_subtitle" to "You can still view your balance, but actions are currently disabled until Twitter Money becomes available in your state.",
        "x_lite_payment_restricted_us_state_unknown_content_title" to "Twitter Money is not available in your state",
        "x_lite_payment_shutdown_content_subtitle" to "A newer version of Twitter is available, and is required to use Money.",
        "x_lite_payments_passkey_setup_benefit_3_subtitle" to "Your account will be secured everywhere you use Twitter",
        "x_lite_pin_added_to_highlights" to "Tweet has been pinned and added to highlights",
        "x_lite_pin_confirmation_message" to "This will appear at the top of your profile and replace any previously pinned tweet.",
        "x_lite_pin_confirmation_title" to "Pin this tweet",
        "x_lite_pinning_failed_message" to "Failed to pin this tweet. Please try again later",
        "x_lite_post_details_post_your_reply" to "Tweet your reply",
        "x_lite_post_details_title" to "Tweet",
        "x_lite_post_engagements" to "Tweet Engagements",
        "x_lite_post_quit_title" to "Save tweet?",
        "x_lite_post_self_thread" to "Tweet all",
        "x_lite_post_tweet" to "Tweet",
        "x_lite_remove_highlight_description" to "This tweet would be removed from the Highlights tab on your profile.",
        "x_lite_sensitive_media_description" to "Select a category, and we’ll put a content warning on this tweet. This helps people avoid content that they don’t want to see.",
        "x_lite_sensitive_media_description_title" to "Put a content warning on this tweet",
        "x_lite_sensitive_media_interstitial_message" to "The tweet author flagged this tweet as showing sensitive content.",
        "x_lite_settings_data_saver_summary" to "When enabled, videos won’t autoplay and lower-quality images load. This automatically reduces your data usage for all Twitter accounts on this device.",
        "x_lite_settings_data_usage_item_detail" to "Limit how Twitter uses some of your network data. These settings affect all the Twitter accounts on this device.",
        "x_lite_simple_tweets_protected_body" to "Only confirmed followers have access to @%s’s tweets and complete profile. Tap the \'Follow\' button to send a follow request.",
        "x_lite_soft_intervention_pivot_government_required" to "Twitter is legally required to provide this notice.",
        "x_lite_translate_tweet_error" to "Unable to translate this tweet. Please try again later.",
        "x_lite_translate_tweet_show" to "Translate tweet",
        "x_lite_tweet_added_to_your_bookmarks" to "Tweet added to your Bookmarks",
        "x_lite_tweet_analytics_title" to "Tweet activity",
        "x_lite_tweet_fab_item" to "Tweet",
        "x_lite_tweet_load_failed" to "Failed to load tweet.",
        "x_lite_tweet_removed_from_your_bookmarks" to "Tweet removed from your Bookmarks",
        "x_lite_tweet_title" to "Tweet",
        "x_lite_tweets_delete_status_error" to "Cannot delete tweet. Please try again later.",
        "x_lite_tweets_delete_title" to "Delete tweet?",
        "x_lite_tweets_protected_title" to "These tweets are protected.",
        "x_lite_tweets_retweet" to "Retweet",
        "x_lite_tweets_undo_retweet_vertical" to "Undo Retweet",
        "x_lite_unpin_confirmation_title" to "Unpin tweet from your profile?",
        "x_lite_unpinning_failed_message" to "Failed to unpin this tweet. Please try again later",
        "x_lite_users_destroy_friendship_message" to "Their tweets will no longer appear in your home timeline. You can still view their profile, unless their tweets are protected.",
        "x_lite_users_unblock_message_when_view_enabled" to "They will be able to follow you and engage with your tweets. (If the account is protected they\'ll have to re-request to follow)",
        "x_lite_verification_protected_desc" to "This account has its tweets protected. Only their followers can read them.",
        "x_lite_view_count_dialog_description" to "Times this tweet was seen. To learn more, visit the {{}}Help Centre{{}}.",
        "x_lite_xchat_empty_convo_list_ui_subtext" to "Drop a line, share tweets and more with private conversations between you and others on Twitter.",
        "xchat_empty_convo_list_ui_subtext" to "Drop a line, share tweets and more with private conversations between you and others on Twitter.",
        "settings_subscription_title" to "Twitter Blue",
        "settings_subscription_summary" to "Manage your subscription’s features including Undo Tweet timing.",
        "subscriptions_drawer_menu_title" to "Blue",
        "twitter_blue_settings_title" to "Twitter Blue"
    )
}
